### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by DougHall** [miyako/4d-plugin-curl-v2#10]
There really needs to be several examples in the documentation. Start simple, like how you would download a particular file. Then show how would you upload a file. Reading curl documentation to try and figure all of this out is a bit overwhelming. I've personally spent the past several hours trying to learn how to upload a file via sftp, with a username/password. This should be easy!!

**Comment by miyako** [comment]
please take into account that:

* you are posting to an old repository that has been superseded by [v3](https://github.com/miyako/4d-plugin-curl-v3)
* the project is open and free to use; anybody can sign up and participate, not just coding but also documenting
* examples are provided in the sample project. for example [here](https://github.com/miyako/4d-plugin-curl-v3/blob/main/curl/test/Project/Sources/Methods/TEST_ftp_upload.4dm)

**Comment by DougHall** [comment]
Okay, thanks for pointing me in the right direction. Also, thanks for all you’re doing! I’ll try to help, if I can.

Doug Hall
