### ISSUE TITLE
supported 4D version

### ISSUE THREAD

**Issue by prachijain78** [miyako/4d-plugin-curl-v2#11]
Will this plugin work for an older 4D version like 14.3?
I need to use a command like cURL to invoke a rest API from 4D, but the LAUNCH EXTERNAL PROCESS is giving me trouble in a client-server architecture, it does work in a standalone 4D app though. I am wondering if instead of trying to use LEP, will this plugin work for me?

Thanks,
Prachi

**Comment by miyako** [comment]
maybe. 

it also depends on the OS version.
