### ISSUE TITLE
mac-arm platform for 4d-plugin-curl-V2

### ISSUE THREAD

**Issue by michelottiABV** [miyako/4d-plugin-curl-v2#12]
Hello, do you have the possibility to include in this plugin the compilation for mac-arm processors ?

**Comment by miyako** [comment]
I would rather not maintain v2. 

is there reason for not using v3?

**Comment by michelottiABV** [comment]
I'm sincerely sorry for this useless question, I just hadn't seen that there was a version 3.
I get version 3 immediately.
Thanks very much

**Comment by miyako** [comment]
it's not a useless question, I should have added a link to v3 in the README.
