### ISSUE TITLE
Certificate with RSASSA-PSS padding

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-curl-v2#3]
Hi Keisuke,

we're having trouble using cURL (for a HTTPS POST) with a specific certificate. This certificate uses RSASSA-PSS padding and the corresponding private key has a length of 4.096 bits. cURL always yields cURL error 58, the log file contains:

TCP_NODELAY set
Connected to verarbeitung.gkv-kommunikationsserver.de (91.198.86.115) port 443 (#11)
ALPN, offering h2
ALPN, offering http/1.1
could not load ASN1 client certificate, OpenSSL error error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak, (no key found, wrong pass phrase, or wrong file format?)
Closing connection 11

Using another certificate with a private key length of 2.048 bits and not using RSASSA-PSS padding, everything is OK, the log file contains:

TCP_NODELAY set
Connected to verarbeitung.gkv-kommunikationsserver.de (91.198.86.115) port 443 (#10)
ALPN, offering h2
ALPN, offering http/1.1
TLSv1.2 (OUT), TLS handshake, Client hello (1):
TLSv1.2 (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (IN), TLS handshake, Server key exchange (12):
TLSv1.2 (IN), TLS handshake, Server finished (14):
TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
TLSv1.2 (OUT), TLS handshake, Finished (20):
TLSv1.2 (IN), TLS handshake, Finished (20):
SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
…

Are there any known issues with this type of certificate? Or did I miss some option to be set?

Tests were done with 4D v18, macOS 10.14.6, cURL-Plugin-v2 Version 3.7.

BTW: cURL-Plugin Version 1.1 (carbon branch) worked without problems with this type of certificate.

If you need more information like the certificate itself, just let me know where to upload it.

Thanks and best regards, Jörg

**Comment by miyako** [comment]
that was supposed to the benefits of using a 3rd party library and echoing its error messages. you should Google 

"ca md too weak, (no key found, wrong pass phrase, or wrong file format?)"

and other messages.

**Comment by joerg-eyring** [comment]
Hi Keisuke,

sorry for bothering you again. I wouldn't have asked you and opened an issue when I hadn't tested cURL via command line beforehand. The following cURL command succeeds without any issues:

curl --cert cert_new.cer --cert-type DER --key privKey_new.pem --key-type PEM --ssl --data-binary @data.xml https://verarbeitung.gkv.de/…

The error message returned from your cURL-Plugin-v2 is imho completely misleading, because the certificate in question doesn't use any old md's. I thought I was precisely enough this time explaining that this certificate uses RSASSA-PSS padding. Here's a part of the ASN1 structure:

    0:d=0  hl=4 l=1456 cons: SEQUENCE          
    4:d=1  hl=4 l= 872 cons:  SEQUENCE          
    8:d=2  hl=2 l=   3 cons:   cont [ 0 ]        
   10:d=3  hl=2 l=   1 prim:    INTEGER           :02
   13:d=2  hl=2 l=   3 prim:   INTEGER           :0F51F1
   18:d=2  hl=2 l=  61 cons:   SEQUENCE          
   20:d=3  hl=2 l=   9 prim:    OBJECT            :rsassaPss
   31:d=3  hl=2 l=  48 cons:    SEQUENCE          
   33:d=4  hl=2 l=  13 cons:     cont [ 0 ]        
   35:d=5  hl=2 l=  11 cons:      SEQUENCE          
   37:d=6  hl=2 l=   9 prim:       OBJECT            :sha256
   48:d=4  hl=2 l=  26 cons:     cont [ 1 ]        
   50:d=5  hl=2 l=  24 cons:      SEQUENCE          
   52:d=6  hl=2 l=   9 prim:       OBJECT            :mgf1
   63:d=6  hl=2 l=  11 cons:       SEQUENCE          
   65:d=7  hl=2 l=   9 prim:        OBJECT            :sha256
   76:d=4  hl=2 l=   3 cons:     cont [ 2 ]        
   78:d=5  hl=2 l=   1 prim:      INTEGER           :20
   81:d=2  hl=2 l=  57 cons:   SEQUENCE          
   83:d=3  hl=2 l=  11 cons:    SET               
   85:d=4  hl=2 l=   9 cons:     SEQUENCE          
   87:d=5  hl=2 l=   3 prim:      OBJECT            :countryName
   92:d=5  hl=2 l=   2 prim:      PRINTABLESTRING   :DE
   96:d=3  hl=2 l=  42 cons:    SET               
   98:d=4  hl=2 l=  40 cons:     SEQUENCE          
  100:d=5  hl=2 l=   3 prim:      OBJECT            :organizationName
  105:d=5  hl=2 l=  33 prim:      PRINTABLESTRING   :ITSG TrustCenter fuer Arbeitgeber
  140:d=2  hl=2 l=  30 cons:   SEQUENCE          
  142:d=3  hl=2 l=  13 prim:    UTCTIME           :200103000000Z
  157:d=3  hl=2 l=  13 prim:    UTCTIME           :230102235959Z

Compared to an older certificate which works with cURL-Plugin-v2:

    0:d=0  hl=4 l= 836 cons: SEQUENCE          
    4:d=1  hl=4 l= 556 cons:  SEQUENCE          
    8:d=2  hl=2 l=   3 cons:   cont [ 0 ]        
   10:d=3  hl=2 l=   1 prim:    INTEGER           :02
   13:d=2  hl=2 l=   3 prim:   INTEGER           :0D0E83
   18:d=2  hl=2 l=  13 cons:   SEQUENCE          
   20:d=3  hl=2 l=   9 prim:    OBJECT            :sha256WithRSAEncryption
   31:d=3  hl=2 l=   0 prim:    NULL              
   33:d=2  hl=2 l=  57 cons:   SEQUENCE          
   35:d=3  hl=2 l=  11 cons:    SET               
   37:d=4  hl=2 l=   9 cons:     SEQUENCE          
   39:d=5  hl=2 l=   3 prim:      OBJECT            :countryName
   44:d=5  hl=2 l=   2 prim:      PRINTABLESTRING   :DE
   48:d=3  hl=2 l=  42 cons:    SET               
   50:d=4  hl=2 l=  40 cons:     SEQUENCE          
   52:d=5  hl=2 l=   3 prim:      OBJECT            :organizationName
   57:d=5  hl=2 l=  33 prim:      PRINTABLESTRING   :ITSG TrustCenter fuer Arbeitgeber
   92:d=2  hl=2 l=  30 cons:   SEQUENCE          
   94:d=3  hl=2 l=  13 prim:    UTCTIME           :190903000000Z
  109:d=3  hl=2 l=  13 prim:    UTCTIME           :220902235959Z
  124:d=2  hl=3 l= 143 cons:   SEQUENCE          

As you can see there's no 'weak' message digest in the first (= new) certificate, in fact it's using rsassa-pss with sha-256 and mgf1.

cURL from command line works without problems using each certificate.
And sorry for repeating a sentence from my first post (I know you don't like looking back): cURL-Plugin Version 1.1 (carbon branch) worked without problems with this type of certificate.

Please take a couple of minutes thinking about what the reason could be. We need this version of cURL-Plugin-v2, because the old (carbon branch) version 1.1 uses SDK's older than 10.9 which prevents notarization of our 4D v18-based app at Apple's notary service.

Thanks for your understanding and best regards, Jörg

**Comment by miyako** [comment]
the argument "it works on command line curl" is kind of irrelevant because it says nothing about libcurl, libssh2 or openssl version. 

openssl 1.0 is a world different from openssl 1.1. 

that said, do you think ``--cert-type DER`` is the missing piece?

have you tried converting it to a different (PEM) format?

see 

https://forums.4d.com/Post/EN/31497545/1/31509027

**Comment by joerg-eyring** [comment]
I tried all combinations for $options.SSLCERTTYPE/$options.SSLKEYTYPE: DER/DER, DER/PEM, PEM/DER, PEM/PEM at no avail. cURL always returns error 58.

I'm just wondering why the libraries (libcurl/openssl) you're using in cURL-Plugin-v2 cannot handle this type of certificate, while the "old" cURL-Plugin 1.1 (carbon branch) did the job perfectly, 32-bit and 64-bit.

We're dealing with this type of certificate without any problems in out self-written plugin for handling CMS messages (sign, encrypt, decrypt, verify) with OpenSSL 1.1.1d, 32-bit and 64-bit.

We're compiling OpenSSL from scratch for 32-bit/64-bit as static libraries, for Windows separate libs, for macOS as a fat file. What OpenSSL version have you been using for cURL-Plugin v2? And did you compile OpenSSL on your own?

Jörg

**Comment by joerg-eyring** [comment]
Just for fun I took the source code from cURL-Plugin-v2 (3.7) and rebuilt the plugin linking it with our libcrypto.a/libssl.a.

The OpenSSL error (…ca md too weak…) mentioned in the first post is gone! So I assume there's something wrong with your libcrypto.a/libssl.a.

But then another problem shows up that the local issuer certificate cannot be loaded (probably from cURL itself). Don't know what's happening here…

TCP_NODELAY set
Connected to verarbeitung.gkv-kommunikationsserver.de (91.198.86.115) port 443 (#0)
ALPN, offering h2
ALPN, offering http/1.1
(304) (OUT), TLS handshake, Client hello (1):
(304) (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (OUT), TLS alert, unknown CA (560):
SSL certificate problem: unable to get local issuer certificate
Closing connection 0

Maybe this helps tracking down the issue…
Regards, Jörg

**Comment by joerg-eyring** [comment]
OK, I supplied the $options.CAINFO with a proper "cacerts.pem" and now it works :-)

TCP_NODELAY set
Connected to verarbeitung.gkv-kommunikationsserver.de (91.198.86.115) port 443 (#0)
ALPN, offering h2
ALPN, offering http/1.1
successfully set certificate verify locations:
  CAfile: /Users/admin/Desktop/cacert.pem
  CApath: none
(304) (OUT), TLS handshake, Client hello (1):
(304) (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (IN), TLS handshake, Server key exchange (12):
TLSv1.2 (IN), TLS handshake, Server finished (14):
TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
TLSv1.2 (OUT), TLS handshake, Finished (20):
TLSv1.2 (IN), TLS handshake, Finished (20):
SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
ALPN, server did not agree to a protocol
Server certificate:
 subject: C=DE; ST=Hessen; L=Heusenstamm; OU=Services und Betrieb; O=ITSG Informationstechn. Servicestelle d. gesetzl. KV GmbH; CN=*.gkv-kommunikationsserver.de
 start date: Nov 11 09:13:14 2019 GMT
 expire date: Jan 26 09:32:40 2022 GMT
 subjectAltName: host "verarbeitung.gkv-kommunikationsserver.de" matched cert's "*.gkv-kommunikationsserver.de"
 issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
 SSL certificate verify ok.
We are completely uploaded and fine
TLSv1.2 (IN), TLS handshake, Hello request (0):
TLSv1.2 (OUT), TLS handshake, Client hello (1):
TLSv1.2 (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (IN), TLS handshake, Server key exchange (12):
TLSv1.2 (IN), TLS handshake, Request CERT (13):
TLSv1.2 (IN), TLS handshake, Server finished (14):
TLSv1.2 (OUT), TLS handshake, Certificate (11):
TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
TLSv1.2 (OUT), TLS handshake, CERT verify (15):
TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
TLSv1.2 (OUT), TLS handshake, Finished (20):
TLSv1.2 (IN), TLS handshake, Finished (20):

So my conclusion is that the libcrypto.a/libssl.a you're using definitely have an issue.
Would you please check and post a new release of cURL-Plugin-v2?

Thank you and best regards, Jörg

**Comment by miyako** [comment]
Is there a reason why you would only share hints but not the files to solve the issue?

**Comment by miyako** [comment]
also, could you please provide a link when you refer to "cURL-Plugin Version 1.1 (carbon branch)"

I have no idea what that is.

**Comment by joerg-eyring** [comment]
Hi Keisuke,

reviewing the discussion in this thread I got the impression that you weren't really interested in getting support tracking down this issue.

There's just one reason for not sharing more information -> I don't have a link where to upload some files.

a) I offered to upload the certificate in question -> no answer
b) I asked whether you're building OpenSSL on your own -> no answer

I'd be happy to provide you with "our" OpenSSL libraries, again I just need a link where to upload them.

But I think this will not be helpful for the future:

a) If you build OpenSSL on your own, you might want to check your ./configure process
b) If you rely on libraries from another source, you might want to check the sources

And yes, sorry for a mistake on my side: I didn't mean cURL-Plugin 1.1, in fact it's 1.0 ;-) Still working reliably in v17…

Regards, Jörg

**Comment by joerg-eyring** [comment]
Ups, I'm not that familiar with Github, just discoverd that I can attach files :-(

[OpenSSL 1.1.1d macOS.zip](https://github.com/miyako/4d-plugin-curl-v2/files/4210842/OpenSSL.1.1.1d.macOS.zip)

[OpenSSL 1.1.1d-x64 Windows.zip](https://github.com/miyako/4d-plugin-curl-v2/files/4210843/OpenSSL.1.1.1d-x64.Windows.zip)

[OpenSSL 1.1.1d-x86 Windows.zip](https://github.com/miyako/4d-plugin-curl-v2/files/4210844/OpenSSL.1.1.1d-x86.Windows.zip)

HTH, Jörg
