### ISSUE TITLE
Not supported READDATA option (problem to send big file)

### ISSUE THREAD

**Issue by PierreTavenard** [miyako/4d-plugin-curl-v2#7]
Hello Miyako,

Here the code i use, it works fine : 

$URL:="sftp://"+OB Lire($SFTPparam;"Adresse")+$EndFilePath

$Options:=New Object
$Options.URL:=$URL
$Options.USERPWD:=OB Lire($SFTPparam;"Identifiant")+":"+OB Lire($SFTPparam;"Mdp")
//$Options.READDATA:=$StartFilePath
$Options.UPLOAD:=1
$Options.CONNECTTIMEOUT:=<>kSFTP_Connect_Time_Out
$Options.LOW_SPEED_TIME:=<>kSFTP_Curl_Operation_Time_Out
$Options.LOW_SPEED_LIMIT:=10

C_BLOB($in;$out)
DOCUMENT VERS BLOB($StartFilePath;$in)
$ErreurNum:=cURL (JSON Stringify($Options);$in;$out;$CallBack;$TransfertInfo;$HeaderInfo)

**Problem is when the file i want to send is to big to be in a 4D blob.
i would like to use this code :** 

$URL:="sftp://"+OB Lire($SFTPparam;"Adresse")+$EndFilePath

$Options:=New Object
$Options.URL:=$URL
$Options.USERPWD:=OB Lire($SFTPparam;"Identifiant")+":"+OB Lire($SFTPparam;"Mdp")
$Options.READDATA:=$StartFilePath
$Options.UPLOAD:=1
$Options.CONNECTTIMEOUT:=<>kSFTP_Connect_Time_Out
$Options.LOW_SPEED_TIME:=<>kSFTP_Curl_Operation_Time_Out
$Options.LOW_SPEED_LIMIT:=10

C_BLOB($in;$out)
//DOCUMENT VERS BLOB($StartFilePath;$in)
$ErreurNum:=cURL (JSON Stringify($Options);$in;$out;$CallBack;$TransfertInfo;$HeaderInfo)

But this doesn't work. the READDATA option is listed as not supported option in your READMME file.
This was working on your v1 plugin.
Is there an other solution to send the file with SFTP without the necessity to create a blob in 4D ?

Thank you very much for everything.

Pierre Tavenard

**Comment by miyako** [comment]
```4d
//$Options.READDATA:=$StartFilePath
DOCUMENT VERS BLOB($StartFilePath;$in)
```

it is not mandatory to use a BLOB.
if you pass a path in READDATA,
it will be process directly by the plugin.
$in is ignored in that case.

```4d
$Options.READDATA:=$StartFilePath
//DOCUMENT VERS BLOB($StartFilePath;$in)
```

without a reproducible example I can not say why the code does not work.

sorry about that.

> But this doesn't work. the READDATA option is listed as not supported option in your README file.

it is not supported, in the sense that it is not used directly in the manner that cURL defines it.

in your example, it looks like `$EndFilePath` is slash delimited and `$StartFilePath` is colon (or backslash) delimited. is that right?

**Comment by PierreTavenard** [comment]
Can i send you an email with a 4dbase example ? 
i created you a sftp user on our serveur

**Comment by miyako** [comment]
Yes, that will help to debug.

**Comment by PierreTavenard** [comment]
Here we go, mail sent

Thanks

**Comment by miyako** [comment]
I found the problem.

the Mac version has not issues, the problem was a typo in the windows code.

`CURLOPT_READDATA`, `CURLOPT_WRITEDATA` was using the wrong encoding.
