### ISSUE TITLE
cURL command not detected as a command since the last update (5 days ago)

### ISSUE THREAD

**Issue by PierreTavenard** [miyako/4d-plugin-curl-v2#8]
Hello Miyako,

Not sure if i'm doing something wrong, bur since your last update (to correct de READDATA WRITEDATA problems) the cURL command is not detected as a command any more. 

I downloaded the last cURL.bundle directory and replace it in the plugin folder

Something strange : the codeResources, manifest.json files are not any more in the content file

Thanks Miyako

**Comment by miyako** [comment]
if you are using v17, you need to move manifest.json one level up, to contents.

**Comment by PierreTavenard** [comment]
OK, it works, thank you.
Yes i'm using v17
