### ISSUE TITLE
Issues with AUTH

### ISSUE THREAD

**Issue by mw-program** [miyako/4d-plugin-curl-v2#9]
Hi, I think I found an issue.
I try to use this plugin (with 4D macOS) to send emails via smtp and im not able to login to the server.(535 Incorrect authentication data)
The possible options are PLAIN and LOGIN. the plugin selected PLAIN and Uses the Username two times like this 
UsernameUsernamePassword.
Is it possible to fix that or to switch to AUTH LOGIN?

**Comment by miyako** [comment]
how did you pass your credentials?

* `smtp://user:pass@server.com`
* [USERPWD](https://curl.se/libcurl/c/CURLOPT_USERPWD.html)
* [USERNAME](https://curl.se/libcurl/c/CURLOPT_USERNAME.html)

the plugin is just a wrapper, you might want to Google "libcurl smtp 535" for more information.

also see [LOGIN_OPTIONS](https://curl.se/libcurl/c/CURLOPT_LOGIN_OPTIONS.html)

**Comment by mw-program** [comment]
OB SET($Options;"PASSWORD";$Password)
OB SET($Options;"USERNAME";$Username)
$err:=cURL (JSON Stringify($Options);$Request;$Response;$callback;$TransferInfo;$HeaderInfo)

**Comment by mw-program** [comment]
AUTH via LOGIN works perfect, thanks
